name = "mrdn-query"
main = "src/index.ts"
compatibility_date = "2026-04-01"

[vars]
WORKER_ENV = "production"

# KV namespace for signal membership + data metadata
[[kv_namespaces]]
binding = "MQL_KV"
id = "04353bca28bc4a78bb51f170adccfd91"

[[d1_databases]]
binding = "DB"
database_name = "mrdn-db"
database_id = "402113d7-e7c5-4584-b932-40e76ea7963f"
